#! /bin/sh

daemon sxhkd
daemon xscreensaver
rescuetime&

feh --bg-center $(find ~/Pictures/wallpapers -type f | shuf -n 1)
~/.config/polybar/launch.sh &

bspc monitor HDMI-0 I II III IV
bspc monitor DP-2 V VI VII VIII
bspc monitor DP-0 IX X

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding          1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config ignore_ewmh_focus    true

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
